<?php

namespace AppBundle\Repository;

/**
 * cuisineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cuisineRepository extends \Doctrine\ORM\EntityRepository
{
}
