<?php

namespace AppBundle\Repository;

/**
 * meal_unavailableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class meal_unavailableRepository extends \Doctrine\ORM\EntityRepository
{
}
