<?php

namespace AppBundle\Repository;

/**
 * mealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mealRepository extends \Doctrine\ORM\EntityRepository
{
}
