<?php

namespace AppBundle\Repository;

/**
 * offerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offerRepository extends \Doctrine\ORM\EntityRepository
{
}
