<?php

namespace AppBundle\Repository;

/**
 * registered_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class registered_userRepository extends \Doctrine\ORM\EntityRepository
{
}
