<?php

namespace AppBundle\Repository;

/**
 * reservation_restRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservation_restRepository extends \Doctrine\ORM\EntityRepository
{
}
