<?php

namespace AppBundle\Repository;

/**
 * reservation_mealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservation_mealRepository extends \Doctrine\ORM\EntityRepository
{
}
