<?php

namespace AppBundle\Repository;

/**
 * restaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class restaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
