<?php

namespace AppBundle\Repository;

/**
 * rest_imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rest_imageRepository extends \Doctrine\ORM\EntityRepository
{
}
